mode: 7
tag: LPlans_4000_patch192_fromscratch_final
planner: nnUNetPlannerResEncL
plans_name: nnUNetResEncUNetLPlans
trainer: nnUNetTrainer_4000epochs
patch_size: 192
batch_size: 1
pretrained_from_mode: null
